kind: pipeline
name: default
type: docker
concurrency:
  limit: 1

trigger:
  branch:
    - main
  event:
    - push

steps:
- name: drone-test
  image: docker
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - docker compose up -f docker-compose.yaml
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock