kind: pipeline
name: default
type: docker
concurrency:
  limit: 1

trigger:
  branch:
    - main
  event:
    - push

steps:
- name: drone-test2
  image: docker:latest
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - up -f docker-compose.yml
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock