kind: pipeline
name: default
#type: docker
type: exec
concurrency:
  limit: 1



trigger:
  branch:
    - main
  event:
    - push

steps:
- name: drone-test
  environment:
    DRONE_REPO_NAME: iot
#  image: docker
#  volumes:
#  - name: docker_sock
#    path: /var/run/docker.sock
  commands:
  - docker compose -f docker-compose.yml up
#volumes:
#  - name: docker_sock
#    host:
#      path: /var/run/docker.sock