kind: pipeline
name: default
type: docker
concurrency:
  limit: 1

trigger:
  branch:
    - main
  event:
    - push

steps:
- name: drone-test2
  image: docker/compose:1.29.2
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - up -f docker-compose.yaml
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock